services:
  aws:
    build: ./aws
    volumes:
      - config:/config
    networks:
      - bridge-network
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4566/_localstack/init | jq -e '.completed.READY == true'"]
      interval: 2s
      retries: 100

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    # .env files are only used for dev, and exclusively to set AWS values
    # AWS Secret Manager is used for all secrets
    command: bun --env-file=/config/.env.server --watch run src/index.ts
    volumes:
      - ./server/:/app/server/
      - ./shared/:/app/shared/
      - config:/config
    networks:
      - bridge-network
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      aws:
        condition: service_healthy

  processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    # .env files are only used for dev, and exclusively to set AWS values
    # AWS Secret Manager is used for all secrets
    command: bun --env-file=/config/.env.processor --watch run src/index.ts
    volumes:
      - ./processor/:/app/processor/
      - ./shared/:/app/shared/
      - config:/config
    networks:
      - bridge-network
    depends_on:
      aws:
        condition: service_healthy

  engine:
    build:
      context: ./engine
    networks:
      - bridge-network
    expose:
      - "8000"

networks:
  bridge-network:
    driver: bridge

volumes:
  config: