services:
  processor:
    build:
      context: ./processor
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-eu-west-1}
    depends_on:
      - engine
    networks:
      - engine-network

  engine:
    build:
      context: ./engine
    networks:
      - engine-network
    expose:
          - "8000"
networks:
  engine-network:
    driver: bridge